# Generated by Django 5.1.4 on 2025-01-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, unique=True)),
                ('team', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=10)),
                ('pass_att', models.FloatField()),
                ('pass_cmp', models.FloatField()),
                ('pass_yd', models.FloatField()),
                ('pass_td', models.FloatField()),
                ('interception', models.FloatField()),
                ('rush_att', models.FloatField()),
                ('rush_yd', models.FloatField()),
                ('rush_td', models.FloatField()),
                ('ownership_percentage', models.FloatField()),
                ('points', models.FloatField()),
            ],
        ),
    ]
