# Generated by Django 5.1.4 on 2025-02-03 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('season_type', models.CharField(default='0', max_length=100)),
                ('date', models.CharField(default='0', max_length=100)),
                ('home_team', models.CharField(default='0', max_length=100)),
                ('away_team', models.CharField(default='0', max_length=100)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('current_play', models.CharField(default='0', max_length=200)),
                ('week', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(default='0', max_length=100)),
                ('position', models.CharField(default='0', max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('team', models.CharField(default='0', max_length=100)),
                ('location', models.CharField(default='0', max_length=100)),
                ('weight', models.FloatField(default=0)),
                ('displayHeight', models.CharField(default=0, max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('experience', models.CharField(default='0', max_length=100)),
                ('jersey', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Def_Stats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pts_allowed', models.IntegerField(default=0)),
                ('inter', models.IntegerField(default=0)),
                ('sacks', models.IntegerField(default=0)),
                ('safties', models.IntegerField(default=0)),
                ('touchdowns', models.IntegerField(default=0)),
                ('forc_fum', models.IntegerField(default=0)),
                ('fumble_rec', models.IntegerField(default=0)),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='all_players.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_players.player')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Stats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='0', max_length=20)),
                ('lastName', models.CharField(default='0', max_length=20)),
                ('week', models.IntegerField(default=0)),
                ('pass_att', models.IntegerField(default=0)),
                ('completions', models.IntegerField(default=0)),
                ('completions_perc', models.FloatField(default=0)),
                ('pass_yards', models.IntegerField(default=0)),
                ('avg_pass_yards_completions', models.FloatField(default=0)),
                ('pass_tds', models.IntegerField(default=0)),
                ('ints', models.IntegerField(default=0)),
                ('sacks', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('targets', models.IntegerField(default=0)),
                ('avg_recieving_yards_perCatch', models.FloatField(default=0)),
                ('receiving_yards', models.FloatField(default=0)),
                ('receiving_tds', models.IntegerField(default=0)),
                ('carrys', models.IntegerField(default=0)),
                ('rush_yards', models.IntegerField(default=0)),
                ('avg_rush_yards_perCarry', models.FloatField(default=0)),
                ('rush_tds', models.IntegerField(default=0)),
                ('fumbles', models.IntegerField(default=0)),
                ('return_td', models.IntegerField(default=0)),
                ('two_pt_made', models.IntegerField(default=0)),
                ('kick_1_19', models.IntegerField(default=0)),
                ('kick_20_29', models.IntegerField(default=0)),
                ('kick_30_39', models.IntegerField(default=0)),
                ('kick_40_49', models.IntegerField(default=0)),
                ('kick_50', models.IntegerField(default=0)),
                ('fg_perc', models.FloatField(default=0)),
                ('fg_attempts', models.IntegerField(default=0)),
                ('fg_made', models.IntegerField(default=0)),
                ('extra_points_made', models.IntegerField(default=0)),
                ('extra_points_attempts', models.IntegerField(default=0)),
                ('total_fantasy_points', models.FloatField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_players.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_players.player')),
            ],
        ),
    ]
