# Generated by Django 5.1.4 on 2025-01-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_stats',
            name='firstName',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='player_stats',
            name='lastName',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
