# Generated by Django 5.1.4 on 2025-01-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, unique=True)),
                ('team', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='QB',
        ),
    ]
