# Generated by Django 5.1.4 on 2025-02-03 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='def_stats',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_players.game'),
        ),
    ]
