# Generated by Django 5.1.4 on 2025-02-03 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0002_alter_def_stats_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='def_stats',
            name='game',
            field=models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='all_players.game'),
        ),
        migrations.AlterField(
            model_name='def_stats',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='all_players.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='game',
            field=models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='all_players.game'),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='all_players.player'),
        ),
    ]
