# Generated by Django 5.1.4 on 2025-01-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0002_player_stats_firstname_player_stats_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player_stats',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
