# Generated by Django 5.1.4 on 2025-01-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0002_player_delete_qb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='firstName',
            field=models.CharField(default='bobs', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='lastName',
            field=models.CharField(default='burgers', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
