# Generated by Django 5.1.4 on 2025-02-10 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0003_game_week_player_stats_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_leagues', to='all_players.player')),
                ('players', models.ManyToManyField(blank=True, related_name='leagues', to='all_players.player')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_players', models.IntegerField(default=12)),
                ('scoring_system', models.CharField(default='Standard', max_length=100)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='all_players.league')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='all_players.league')),
                ('nfl_players', models.ManyToManyField(blank=True, related_name='nfl_teams', to='all_players.player')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_owned', to='all_players.player')),
                ('players', models.ManyToManyField(related_name='teams', to='all_players.player')),
            ],
        ),
    ]
