# Generated by Django 5.1.4 on 2025-01-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0003_remove_player_player_name_remove_player_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
    ]
