# Generated by Django 5.1.4 on 2025-02-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0003_alter_def_stats_game_alter_def_stats_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='def_stats',
            name='location',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='def_stats',
            name='team',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='def_stats',
            name='total_fantasy_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='def_stats',
            name='week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='total_fantasy_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
