# Generated by Django 5.1.4 on 2025-01-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0004_alter_player_firstname_alter_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='displayHeight',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='experience',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='jersey',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
