# Generated by Django 5.1.4 on 2025-02-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0004_def_stats_location_def_stats_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='def_stats',
            name='proj_fantasy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='player_stats',
            name='proj_fantasy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
