# Generated by Django 5.1.4 on 2025-02-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0005_def_stats_proj_fantasy_player_stats_proj_fantasy'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='headshot',
            field=models.ImageField(default='images/headShots/0.png', upload_to='images/headShots/'),
        ),
        migrations.AddField(
            model_name='player',
            name='news',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='player',
            name='yearly_proj',
            field=models.FloatField(default=0),
        ),
    ]
