# Generated by Django 5.1.4 on 2025-01-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0005_player_age_player_displayheight_player_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
