# Generated by Django 5.1.4 on 2025-01-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0006_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='location',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
