# Generated by Django 5.1.4 on 2025-02-17 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0006_player_headshot_player_news_player_yearly_proj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(default='0', max_length=200)),
                ('text', models.TextField(default='0')),
                ('date', models.CharField(default='0', max_length=100)),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='all_players.player')),
            ],
        ),
    ]
