# Generated by Django 5.1.4 on 2025-01-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0007_player_location_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='QB_Stats',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('games_played', models.IntegerField(default=0)),
                ('total_pass_att', models.IntegerField(default=0)),
                ('total_completions', models.IntegerField(default=0)),
                ('perc_completions', models.FloatField(default=0)),
                ('total_pass_yards', models.IntegerField(default=0)),
                ('avg_pass_yards', models.FloatField(default=0)),
                ('total_pass_tds', models.IntegerField(default=0)),
                ('avg_pass_tds', models.FloatField(default=0)),
                ('total_ints', models.IntegerField(default=0)),
                ('avg_ints', models.FloatField(default=0)),
                ('total_carrys', models.IntegerField(default=0)),
                ('total_rush_yards', models.IntegerField(default=0)),
                ('avg_rush_yards', models.FloatField(default=0)),
                ('total_rush_tds', models.IntegerField(default=0)),
                ('total_sacks', models.IntegerField(default=0)),
                ('avg_sacks', models.FloatField(default=0)),
                ('total_fantasy_points', models.FloatField(default=0)),
                ('avg_fantasy_points', models.FloatField(default=0)),
            ],
        ),
    ]
