# Generated by Django 5.1.4 on 2025-02-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0007_player_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='images/headShots/'),
        ),
    ]
