# Generated by Django 5.1.4 on 2025-02-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0008_alter_player_headshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='news',
        ),
    ]
