# Generated by Django 5.1.4 on 2025-01-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0008_qb_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qb_stats',
            old_name='total_ints',
            new_name='pass_att',
        ),
        migrations.RenameField(
            model_name='qb_stats',
            old_name='games_played',
            new_name='pass_tds',
        ),
        migrations.RenameField(
            model_name='qb_stats',
            old_name='total_carrys',
            new_name='pass_yards',
        ),
        migrations.RenameField(
            model_name='qb_stats',
            old_name='total_completions',
            new_name='rush_tds',
        ),
        migrations.RenameField(
            model_name='qb_stats',
            old_name='total_pass_att',
            new_name='rush_yards',
        ),
        migrations.RenameField(
            model_name='qb_stats',
            old_name='total_pass_tds',
            new_name='sacks',
        ),
        migrations.RemoveField(
            model_name='qb_stats',
            name='avg_fantasy_points',
        ),
        migrations.RemoveField(
            model_name='qb_stats',
            name='avg_ints',
        ),
        migrations.RemoveField(
            model_name='qb_stats',
            name='avg_pass_tds',
        ),
        migrations.RemoveField(
            model_name='qb_stats',
            name='avg_pass_yards',
        ),
        migrations.RemoveField(
            model_name='qb_stats',
            name='avg_sacks',
        ),
        migrations.RemoveField(
            model_name='qb_stats',
            name='total_pass_yards',
        ),
        migrations.RemoveField(
            model_name='qb_stats',
            name='total_rush_tds',
        ),
        migrations.RemoveField(
            model_name='qb_stats',
            name='total_rush_yards',
        ),
        migrations.RemoveField(
            model_name='qb_stats',
            name='total_sacks',
        ),
        migrations.AddField(
            model_name='qb_stats',
            name='avg_pass_yards_completions',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='qb_stats',
            name='carrys',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qb_stats',
            name='completions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qb_stats',
            name='ints',
            field=models.IntegerField(default=0),
        ),
    ]
