# Generated by Django 5.1.4 on 2025-02-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0009_remove_player_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_stats',
            old_name='avg_recieving_yards_perCatch',
            new_name='avg_receiving_yards_perCatch',
        ),
    ]
