# Generated by Django 5.1.4 on 2025-01-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0009_rename_total_ints_qb_stats_pass_att_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Stats',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pass_att', models.IntegerField(default=0)),
                ('completions', models.IntegerField(default=0)),
                ('completions_perc', models.FloatField(default=0)),
                ('pass_yards', models.IntegerField(default=0)),
                ('avg_pass_yards_completions', models.FloatField(default=0)),
                ('pass_tds', models.IntegerField(default=0)),
                ('ints', models.IntegerField(default=0)),
                ('sacks', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('targets', models.IntegerField(default=0)),
                ('recieving_yards', models.IntegerField(default=0)),
                ('avg_recieving_yards', models.FloatField(default=0)),
                ('receiving_tds', models.IntegerField(default=0)),
                ('carrys', models.IntegerField(default=0)),
                ('rush_yards', models.IntegerField(default=0)),
                ('avg_rush_yards', models.FloatField(default=0)),
                ('rush_tds', models.IntegerField(default=0)),
                ('fumbles', models.IntegerField(default=0)),
                ('kick_1_19', models.IntegerField(default=0)),
                ('kick_20_29', models.IntegerField(default=0)),
                ('kick_30_39', models.IntegerField(default=0)),
                ('kick_40_49', models.IntegerField(default=0)),
                ('kick_50', models.IntegerField(default=0)),
                ('fg_perc', models.FloatField(default=0)),
                ('fg_attempts', models.IntegerField(default=0)),
                ('total_fantasy_points', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='QB_Stats',
        ),
    ]
