# Generated by Django 5.1.4 on 2025-01-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0010_player_stats_delete_qb_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('home_team', models.CharField(default='0', max_length=100)),
                ('away_team', models.CharField(default='0', max_length=100)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
            ],
        ),
    ]
