# Generated by Django 5.1.4 on 2025-03-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0006_league_team'),
        ('all_players', '0010_rename_avg_recieving_yards_percatch_player_stats_avg_receiving_yards_percatch'),
    ]

    operations = [
    ]
