# Generated by Django 5.1.4 on 2025-03-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0011_merge_20250307_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
        migrations.AlterField(
            model_name='player',
            name='headshot',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='yearly_proj',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
