# Generated by Django 5.1.4 on 2025-01-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0011_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='season_type',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
