# Generated by Django 5.1.4 on 2025-01-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0012_game_date_game_season_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
