# Generated by Django 5.1.4 on 2025-01-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0013_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_play',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
