# Generated by Django 5.1.4 on 2025-01-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0014_game_current_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_stats',
            name='game_id',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
