# Generated by Django 5.1.4 on 2025-01-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0015_player_stats_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_stats',
            old_name='avg_recieving_yards',
            new_name='avg_recieving_yards_perCatch',
        ),
        migrations.RenameField(
            model_name='player_stats',
            old_name='avg_rush_yards',
            new_name='avg_rush_yards_perCarry',
        ),
        migrations.RemoveField(
            model_name='player_stats',
            name='recieving_yards',
        ),
        migrations.AddField(
            model_name='player_stats',
            name='avg_recieving_yards_perGame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player_stats',
            name='avg_rush_yards_perGame',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player_stats',
            name='extra_points_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player_stats',
            name='extra_points_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player_stats',
            name='fg_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player_stats',
            name='receiving_yards',
            field=models.FloatField(default=0),
        ),
    ]
