# Generated by Django 5.1.4 on 2025-01-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0016_rename_avg_recieving_yards_player_stats_avg_recieving_yards_percatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_stats',
            name='avg_recieving_yards_perGame',
        ),
        migrations.RemoveField(
            model_name='player_stats',
            name='avg_rush_yards_perGame',
        ),
    ]
