# Generated by Django 5.1.4 on 2025-04-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='updated_on_wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
