# Generated by Django 5.1.4 on 2025-03-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_league_profile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='join_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
