# Generated by Django 5.1.4 on 2025-04-24 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_delete_traderequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_players', models.JSONField()),
                ('receiver_players', models.JSONField()),
                ('currency_offered', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency_requested', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests', to='User.league')),
                ('receiver_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trades', to='User.team')),
                ('sender_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trades', to='User.team')),
            ],
        ),
    ]
