# Generated by Django 5.1.4 on 2025-03-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_league_join_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='football_players',
        ),
        migrations.AddField(
            model_name='team',
            name='BN1',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='BN2',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='BN3',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='BN4',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='BN5',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='BN6',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='DEF',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='FLX',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='IR1',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='IR2',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='K',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='QB',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='RB1',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='RB2',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='TE',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='WR1',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='WR2',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
