# Generated by Django 5.1.4 on 2025-03-17 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_team_football_players_team_bn1_team_bn2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.AddField(
            model_name='team',
            name='author',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='ReDraft', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='title',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='User.league'),
        ),
        migrations.DeleteModel(
            name='traditional_redraft',
        ),
    ]
