# Generated by Django 5.1.4 on 2025-03-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_league_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='draftStarted',
            field=models.BooleanField(default=False),
        ),
    ]
