# Generated by Django 5.1.4 on 2025-03-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_league_draftstarted'),
    ]

    operations = [
        
    ]
