# Generated by Django 5.1.4 on 2025-03-17 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_team_football_players_team_bn1_team_bn2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_pick', models.IntegerField(default=1)),
                ('draft_order', models.JSONField()),
                ('picks', models.JSONField(default=list)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.league')),
            ],
        ),
    ]
