# Generated by Django 5.1.4 on 2025-03-24 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='current_pick',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='User.league'),
        ),
    ]
