# Generated by Django 5.1.4 on 2025-03-24 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_team_football_players_remove_team_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
       
        migrations.AddField(
            model_name='league',
            name='draftComplete',
            field=models.BooleanField(default=False),
        ),
       
    ]
