# Generated by Django 5.1.4 on 2025-03-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_team_manager_remove_team_name_team_author_and_more'),
        ('User', '0009_remove_team_football_players_remove_team_manager_and_more'),
    ]

    operations = [
    ]
