# Generated by Django 5.1.4 on 2025-03-24 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_merge_20250324_1716'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(default=0)),
                ('team1score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('team2score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.league')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_team1', to=settings.AUTH_USER_MODEL)),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_team2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
