# Generated by Django 5.1.4 on 2025-03-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_matchup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
